# Generated by Django 5.1.2 on 2024-11-07 18:18

import core.utilits
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLogOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('event_type', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('FAILED', 'Failed'), ('SCHEDULED', 'Scheduled'), ('SUCCEEDED', 'Success')], db_index=True, default='SCHEDULED', max_length=20)),
                ('event_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_context', models.JSONField()),
                ('metadata_version', models.PositiveBigIntegerField(default=1)),
                ('expires_at', models.DateTimeField(default=core.utilits._one_more_day)),
                ('retry', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
    ]
